FROM pytorch/pytorch:1.11.0-cuda11.3-cudnn8-runtime

ENV LC_ALL=en_US.UTF-8 \
    PYTHONUNBUFFERED=1

WORKDIR /home/

COPY requirements.txt /home/

RUN apt-get update && \
    apt-get install -y --no-install-suggests --no-install-recommends software-properties-common && \
    apt-get update && \
    apt-get install -y --no-install-suggests --no-install-recommends \
        git locales gcc g++ && \
    echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
    locale-gen && \
    pip install --upgrade -r requirements.txt && \
    apt-get remove -y git gcc g++ && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY flask_app.py /home/
COPY stable_diffusion.py /home/

ENTRYPOINT python flask_app.py
